/// 1.
// Search
#define DRAGON_SOUL_STRENGTH_MAX 7

// Add above
#if defined(__DS_CHANGE_ATTR__)
enum EDragonSoulChangeAttrMaterialCount
{
	DRAGON_SOUL_CHANGE_ATTR_STEP_LOWEST = 1,
	DRAGON_SOUL_CHANGE_ATTR_STEP_LOW = 3,
	DRAGON_SOUL_CHANGE_ATTR_STEP_MID = 9,
	DRAGON_SOUL_CHANGE_ATTR_STEP_HIGH = 27,
	DRAGON_SOUL_CHANGE_ATTR_STEP_HIGHEST = 81,
};
#endif
